# Generated by Django 3.0.6 on 2020-05-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0002_myuser_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='user_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
