# Generated by Django 3.0.6 on 2020-05-20 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0004_remove_myuser_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='user_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
